const Send_Transaction_Query="Send_Transaction_Query"
const Transaction_Query_Successfull="Transaction_Query_Successfull"
const Transaction_Query_Failure="Transaction_Query_Failure"

export {Send_Transaction_Query,Transaction_Query_Successfull,Transaction_Query_Failure}