const SEND_STATS_QUERY="SEND_STATS_QUERY"
const STATS_QUERY_SUCCESSFULL="STATS_QUERY_SUCCESSFULL"
const STATS_QUERY_FAILURE="STATS_QUERY_FAILURE"



export {SEND_STATS_QUERY,STATS_QUERY_SUCCESSFULL,STATS_QUERY_FAILURE}