const Start_Location_Query="Start_Location_Query"
const Location_Query_Successfull="Location_Query_Successfull"
const Location_Query_Failure="Location_Query_Failure"

export {Start_Location_Query,Location_Query_Successfull,Location_Query_Failure}